# Generated by Django 4.1.2 on 2022-12-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_queryset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
