# Generated by Django 4.1.2 on 2022-12-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_queryset', '0003_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='iscompleted',
        ),
    ]
