# Generated by Django 4.1.2 on 2023-01-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_queryset', '0004_rename_is_completed_task_iscompleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
    ]
